version: '3'

services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testingps
      POSTGRES_USER: sa
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080